"""M8 Evaluation Script — Sequential Factor Gating.

Runs backtest specs through run_from_spec and prints a summary table for
M8 milestone factor evaluation.

Usage:
    python scripts/_m8_evaluate.py
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add src to path so we can import skuld modules
python_root = Path(__file__).parent.parent
sys.path.insert(0, str(python_root / "src"))

from skuld_research.config import load_spec, run_from_spec


def main() -> None:
    """Evaluate specs and write summary report."""
    
    # Define specs to evaluate (label, relative path from python/)
    specs_to_evaluate = [
        ("momentum_only", "configs/preregistered/2026-04-26_momentum_only.yaml"),
        ("momentum_low_vol", "configs/preregistered/2026-04-26_momentum_low_vol.yaml"),
        ("momentum_size", "configs/preregistered/2026-04-26_momentum_size.yaml"),
        ("momentum_low_vol_size", "configs/preregistered/2026-04-26_momentum_low_vol_size.yaml"),
    ]
    
    # Resolve paths
    data_csv = python_root.parent / "data" / "data_long.csv"
    
    results = []
    
    print("=" * 80)
    print("M8 Factor Evaluation")
    print("=" * 80)
    print()
    
    for label, spec_path_rel in specs_to_evaluate:
        spec_path = python_root / spec_path_rel
        print(f"Running: {label} ({spec_path.name})...")
        
        spec = load_spec(spec_path)
        result = run_from_spec(spec, raw_csv_path=data_csv, write_ledger=False)
        
        rolling = result.strategy_rolling
        gating = result.gating
        
        results.append({
            "label": label,
            "spec_hash": result.spec_hash[:12],
            "n_kept_folds": rolling.n_kept_folds,
            "oos_sharpe_raw": rolling.oos_sharpe_raw,
            "oos_sharpe_delisting_adjusted": rolling.oos_sharpe_delisting_adjusted,
            "gating_passes": gating.passes,
            "deflated_sharpe": gating.deflated.sharpe_deflated,
        })
        
        print(f"  -> OOS Sharpe (delisting-adj): {rolling.oos_sharpe_delisting_adjusted:.3f}")
        print(f"  -> Gating: {'PASS' if gating.passes else 'FAIL'}")
        print()
    
    # Print summary table
    print("=" * 80)
    print("Summary Table")
    print("=" * 80)
    print()
    print(f"{'Label':<25} {'Hash':<14} {'Folds':<7} {'Sharpe':<10} {'Sharpe(DL)':<12} {'Gate':<6} {'Deflated':<10}")
    print("-" * 80)
    
    for r in results:
        print(
            f"{r['label']:<25} "
            f"{r['spec_hash']:<14} "
            f"{r['n_kept_folds']:<7} "
            f"{r['oos_sharpe_raw']:<10.3f} "
            f"{r['oos_sharpe_delisting_adjusted']:<12.3f} "
            f"{'PASS' if r['gating_passes'] else 'FAIL':<6} "
            f"{r['deflated_sharpe']:<10.3f}"
        )
    
    print()
    
    # Write markdown summary
    report_dir = python_root / "reports"
    report_dir.mkdir(exist_ok=True)
    report_path = report_dir / "m8_evaluation_summary.md"
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# M8 Factor Evaluation Summary\n\n")
        f.write("Generated by `scripts/_m8_evaluate.py`.\n\n")
        f.write("| Label | Spec Hash | Folds | OOS Sharpe (raw) | OOS Sharpe (DL-adj) | Gating | Deflated Sharpe |\n")
        f.write("|-------|-----------|-------|------------------|---------------------|--------|------------------|\n")
        
        for r in results:
            f.write(
                f"| {r['label']} "
                f"| `{r['spec_hash']}` "
                f"| {r['n_kept_folds']} "
                f"| {r['oos_sharpe_raw']:.3f} "
                f"| {r['oos_sharpe_delisting_adjusted']:.3f} "
                f"| {'✓' if r['gating_passes'] else '✗'} "
                f"| {r['deflated_sharpe']:.3f} |\n"
            )
    
    print(f"Summary written to: {report_path}")
    print()


if __name__ == "__main__":
    main()
